opensource-programs/pebble-2.6.4/src/src/main/java/net/sourceforge/pebble/domain/Comment.java
/*
 * Copyright (c) 2003-2011, Simon Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   - Neither the name of Pebble nor the names of its contributors may
 *     be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package net.sourceforge.pebble.domain;

import net.sourceforge.pebble.api.event.comment.CommentEvent;
import net.sourceforge.pebble.util.StringUtils;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Represents a blog comment.
 *
 * @author    Simon Brown
 */
public class Comment extends Response {

  /** the body of the comment */
  private String body;

  /** the name of the author */
  private String author;

  /** the author's e-mail address */
  private String email;

  /** the author's website */
  private String website;

  /** the parent comment, if applicable */
  private Comment parent;

  /** the URL of the avatar */
  private String avatar;

  /** the collection of nested comments */
  private List comments = new ArrayList();

  /** a flag to indicate whether the user was authenticated when the comment was left */
  private boolean authenticated = false;

  public Comment() {
  }

  /**
   * Creates a new comment with the specified properties.
   *
   * @param title        the comment title
   * @param body        the comment body
   * @param author      the name of the author
   * @param website     the author's website
   * @param ipAddress the IP address of the author
   * @param date        the date that this comment was left
   * @param state       the state of the comment
   * @param blogEntry   the owning blog entry
   */
  Comment(String title, String body, String author, String email, String website, String avatar, String ipAddress, Date date, State state, BlogEntry blogEntry) {
    super(title, ipAddress, date, state, blogEntry);

    setBody(body);
    setAuthor(author);
    setEmail(email);
    setWebsite(website);
    setAvatar(avatar);
  }

  /**
   * Gets the body of this comment.
   *
   * @return    the body of this comment as a String
   */
  public String getBody() {
    return body;
  }

  /**
   * Gets the content of this response.
   *
   * @return a String
   */
  public String getContent() {
    return getBody();
  }

  /**
   * Gets the body of this comment, truncated and without HTML tags.
   *
   * @return    the body of this comment as a String
   */
  public String getTruncatedBody() {
    return this.getTruncatedContent();
  }

  /**
   * Sets the title of this comment.
   *
   * @param   title    the title of this comment as a String
   */
  public void setTitle(String title) {
    if (title == null || title.length() == 0) {
      if (blogEntry != null) {
        this.title = "Re: " + blogEntry.getTitle();
      } else {
        this.title = "Comment";
      }
    } else {
      this.title = title;
    }
  }

  /**
   * Sets the body of this comment.
   *
   * @param   body    the body of this comment as a String
   */
  public void setBody(String body) {
    if (body == null || body.length() == 0) {
      this.body = null;
    } else {
      this.body = body;
    }
  }

  /**
   * Gets the name of the author.
   *
   * @return    the name of the author as a String
   */
  public String getAuthor() {
    return author;
  }

  /**
   * Gets the name of the source of this response.
   *
   * @return a String
   */
  public String getSourceName() {
    return getAuthor();
  }

  /**
   * Sets the author of this blog comment. If an author isn't specified,
   * the author is set to be "Anonymous".
   *
   * @param author    the name of the author
   */
  public void setAuthor(String author) {
    if (author == null || author.length() == 0) {
      this.author = "Anonymous";
    } else {
      this.author = author;
    }
  }

  /**
   * Gets the author's e-mail address.
   *
   * @return    the author's e-mail address as a String
   */
  public String getEmail() {
    return email;
  }

  /**
   * Sets the author's e-mail address.
   *
   * @param email   the e-mail address
   */
  public void setEmail(String email) {
    if (email == null || email.length() == 0) {
      this.email = null;
    } else {
      this.email = StringUtils.transformHTML(email);
    }
  }

  /**
   * Gets the author's website.
   *
   * @return    the author's website as a String
   */
  public String getWebsite() {
    return website;
  }

  /**
   * Gets the link to the source of this response.
   *
   * @return a String
   */
  public String getSourceLink() {
    return getWebsite();
  }

  /**
   * Sets the author's website.
   *
   * @param website   the website url
   */
  public void setWebsite(String website) {
    this.website = StringUtils.validateUrl(StringUtils.filterHTML(website));
  }

  /**
   * Gets the permalink for this comment.
   *
   * @return  a URL as a String
   */
  public String getPermalink() {
    if (blogEntry != null) {
      return blogEntry.getLocalPermalink() + "#comment" + getId();
    } else {
      return "";
    }
  }

  /**
   * Gets the avatar URL
   *
   * @return a URL as a String
   */
  public String getAvatar() {
    return avatar;
  }

  /**
   * Sets the avatar URL
   *
   * @param avatar a URL as a String
   */
  public void setAvatar(String avatar) {
    this.avatar = StringUtils.validateUrl(StringUtils.filterHTML(avatar));
  }

  /**
   * Gets the owning comment, if this comment is nested.
   *
   * @return    a Comment instance, or null if this comment isn't nested
   */
  public Comment getParent() {
    return this.parent;
  }

  /**
   * Sets the owning comment.
   *
   * @param parent    the owning Comment instance
   */
  public void setParent(Comment parent) {
    this.parent = parent;
  }

  /**
   * Gets the number of parents that this comment has.
   *
   * @return  the number of parents as an int
   */
  public int getNumberOfParents() {
    int count = 0;
    Comment c = getParent();
    while (c != null) {
      count++;
      c = c.getParent();
    }

    return count;
  }

  /**
   * Adds a child comment.
   *
   * @param comment   the Comment to add
   */
  void addComment(Comment comment) {
    if (comment != null && !comments.contains(comment)) {
      comments.add(comment);
      comment.setParent(this);
    }
  }

  /**
   * Removes a child comment.
   *
   * @param comment   the Comment to be removed
   */
  void removeComment(Comment comment) {
    if (comment != null && comments.contains(comment)) {
      // remove all children
      for (Comment child : getComments()) {
        comment.removeComment(child);
      }

      // then remove the comment itself
      comments.remove(comment);
      comment.setParent(null);

      if (areEventsEnabled()) {
        getBlogEntry().addEvent(new CommentEvent(comment, CommentEvent.COMMENT_REMOVED));
      }
    }
  }

  /**
   * Gets a list of comments, in the order that they were left.
   *
   * @return  a List of Comment instances
   */
  public List<Comment> getComments() {
    return new ArrayList<Comment>(comments);
  }

  /**
   * Creates and returns a copy of this object.
   *
   * @return a clone of this instance.
   * @see Cloneable
   */
  public Object clone() {
    Comment comment = new Comment(title, body, author, email, website, avatar, ipAddress, date, getState(), blogEntry);
    comment.setParent(parent);
    comment.setAuthenticated(authenticated);
    return comment;
  }

  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }

    if (!(o instanceof Comment)) {
      return false;
    }

    Comment comment = (Comment)o;
    return (getId() == comment.getId() && blogEntry.getId().equals(comment.getBlogEntry().getId()));
  }

  public int hashCode() {
    return ("" + getId()).hashCode();
  }

  /**
   * Sets the state of this comment.
   */
  void setState(State s) {
    State previousState = getState();
    super.setState(s);

    if (areEventsEnabled()) {
      if (isApproved() && previousState != State.APPROVED) {
        getBlogEntry().addEvent(new CommentEvent(this, CommentEvent.COMMENT_APPROVED));
      } else if (isRejected() && previousState != State.REJECTED) {
        getBlogEntry().addEvent(new CommentEvent(this, CommentEvent.COMMENT_REJECTED));
      }
    }
  }

  public boolean isAuthenticated() {
    return authenticated;
  }

  public void setAuthenticated(boolean authenticated) {
    this.authenticated = authenticated;
  }

  @Override
  public boolean isHasEmail() {
    return true;
  }
}

opensource-programs/pebble-2.6.4/src/src/main/java/net/sourceforge/pebble/domain/Response.java
/*
 * Copyright (c) 2003-2011, Simon Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   - Neither the name of Pebble nor the names of its contributors may
 *     be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package net.sourceforge.pebble.domain;

import java.util.Calendar;
import java.util.Date;

import net.sourceforge.pebble.util.StringUtils;

/**
 * Represents a response to a blog entry - either a comment or a TrackBack.
 *
 * @author    Simon Brown
 */
public abstract class Response extends Content {

  /** the title */
  protected String title;

  /** the ip address of the author */
  protected String ipAddress;

  /** the date that the trackback was received */
  protected Date date;

  /** the parent blog entry */
  protected BlogEntry blogEntry;

  /** a score used to help identify spam when repsonses are added */
  private int spamScore = 0;

  /**
   * Default, no args constructor.
   */
  public Response() {
  }

  /**
   * Creates a new instance with the specified properties.
   *
   * @param title       the title of the entry
   * @param ipAddress   the IP address of the author
   * @param date        the date that this comment was left
   * @param state       the state of the comment
   * @param blogEntry   the owning blog entry
   */
  Response(String title, String ipAddress, Date date, State state, BlogEntry blogEntry) {
    this.blogEntry = blogEntry;

    setTitle(title);
    setIpAddress(ipAddress);
    setDate(date);
    setState(state);
  }

  /**
   * Gets the id of this comment.
   *
   * @return    the id as a primitive long
   */
  public long getId() {
    return date.getTime();
  }

  /**
   * Gets the globally unique id of this response.
   *
   * @return  a String of the form type/blogEntryId/responseId
   */
  public String getGuid() {
    String s = "";
    if (this instanceof Comment) {
      s = "c/";
    } else if (this instanceof TrackBack) {
      s = "t/";
    }

    s+= getBlogEntry().getId() + "/" + getId();

    return s;
  }

  /**
   * Gets the title.
   *
   * @return  the title as a String
   */
  public String getTitle() {
    return this.title;
  }

  /**
   * Sets the title of the blog entry for this trackback.
   *
   * @param   title   the title as a String
   */
  public void setTitle(String title) {
    this.title = StringUtils.transformHTML(title);
  }

  /**
   * Gets the name of the source of this response.
   *
   * @return  a String
   */
  public abstract String getSourceName();

  /**
   * Gets the link to the source of this response.
   *
   * @return  a String
   */
  public abstract String getSourceLink();

  /**
   * Gets the IP address.
   *
   * @return  the IP address as a String
   */
  public String getIpAddress() {
    return ipAddress;
  }

  /**
   * Sets the IP address.
   *
   * @param ipAddress   the IP address of the responder
   */
  public void setIpAddress(String ipAddress) {
    if (ipAddress == null || ipAddress.length() == 0) {
      this.ipAddress = null;
    } else {
      this.ipAddress = ipAddress;
    }
  }

  /**
   * Gets the date that this response was received.
   *
   * @return    the date as a java.util.Date instance.
   */
  public Date getDate() {
    return date;
  }

  /**
   * Sets the date that this response was received.
   *
   * @param   date    the date as a java.util.Date instance.
   */
  public void setDate(Date date) {
    if (date == null) {
      date = new Date();
    }

    Calendar cal = blogEntry.getBlog().getCalendar();
    cal.setTime(date);
    this.date = cal.getTime();
  }

  /**
   * Gets the owning blog entry.
   *
   * @return    the owning BlogEntry instance
   */
  public BlogEntry getBlogEntry() {
    return blogEntry;
  }

  /**
   * Sets the owning blog entry.
   *
   * @param blogEntry   the owning BlogEntry instance
   */
  void setBlogEntry(BlogEntry blogEntry) {
    this.blogEntry = blogEntry;
  }

  /**
   * Gets the spam score.
   *
   * @return  an int
   */
  public int getSpamScore() {
    return this.spamScore;
  }

  /**
   * Increments the spam score by 1.
   */
  public void incrementSpamScore() {
    this.spamScore++;
  }

  /**
   * Sets the state of this response to rejected.
   */
  public void setRejected() {
    setState(State.REJECTED);
  }

  /**
   * Determines whether this response is rejected.
   *
   * @return  true if the state is rejected, false otherwise
   */
  public boolean isRejected() {
    return getState().equals(State.REJECTED);
  }

  /**
   * Sets the state of this response to approved.
   */
  public void setApproved() {
    setState(State.APPROVED);
  }

  /**
   * Determines whether this response is approved.
   *
   * @return  true if the state is approved, false otherwise
   */
  public boolean isApproved() {
    return getState().equals(State.APPROVED);
  }

  /**
   * Sets the state of this response to pending.
   */
  public void setPending() {
    setState(State.PENDING);
  }

  /**
   * Determines whether this response is pending.
   *
   * @return  true if the state is pending, false otherwise
   */
  public boolean isPending() {
    return getState().equals(State.PENDING);
  }

  /**
   * Whether this response has an email field
   */
  public abstract boolean isHasEmail();

}

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/fragments/commentForm.jsp
<c:if test="${blog.richTextEditorForCommentsEnabled}">
  <script type="text/javascript" src="${pageContext.request.contextPath}/FCKeditor/fckeditor.js"></script>
  <script type="text/javascript">
  window.onload = function()
  {
    var oFCKeditor = new FCKeditor( 'commentBody' ) ;
    oFCKeditor.BasePath = '${pageContext.request.contextPath}/FCKeditor/' ;
    oFCKeditor.Config["CustomConfigurationsPath"] = '${pageContext.request.contextPath}/fckconfig_pebble.js';
    oFCKeditor.ToolbarSet = 'Comment' ;
    oFCKeditor.ReplaceTextarea() ;
  }
  </script>
</c:if>

<form id="commentForm" name="commentForm" action="saveComment.action" method="post" accept-charset="${blog.characterEncoding}">
  <pebble:token/>
  <input type="hidden" name="blogId" value="<c:out value="${blogEntry.blog.id}"/>" />
  <input type="hidden" name="entry" value="<c:out value="${blogEntry.id}"/>" />
  <input type="hidden" name="comment" value="<c:out value="${undecoratedComment.parent.id}"/>" />
  <input type="hidden" name="avatar" value="<c:out value="${undecoratedComment.avatar}"/>"/>

<table width="99%">

  <c:if test="${not empty parentComment}">
  <tr>
    <td colspan="2">
      <c:set var="comment" scope="request" value="${parentComment}"/>
      <c:set var="displayMode" scope="request" value="preview" />
      <div id="parentComment"><jsp:include page="comment.jsp"><jsp:param name="commentIdentifier" value="parentComment"/></jsp:include></div>
      <br />
    </td>
  </tr>
  </c:if>

  <c:if test="${not empty validationContext.errors}">
  <tr>
    <td colspan="2" class="validationError">
      <b><c:out value="${validationContext.numberOfErrors}" /> error(s)</b>
      <ul>
      <c:forEach var="error" items="${validationContext.errors}">
        <li><c:out value="${error.message}"/></li>
      </c:forEach>
      </ul>
      <br />
    </td>
  </tr>
  </c:if>

  <tr>
    <td colspan="2">
      <c:set var="comment" scope="request" value="${decoratedComment}"/>
      <c:set var="displayMode" scope="request" value="preview" />
      <jsp:include page="comment.jsp"><jsp:param name="commentIdentifier" value="previewComment"/></jsp:include>
      <br />
    </td>
  </tr>

  <c:set var="comment" scope="request" value="${undecoratedComment}"/>

  <tr>
    <td valign="top"><b><fmt:message key="comment.title" /></b></td>
    <td><input type="text" name="title" size="40" value="<c:out value="${comment.title}"/>"/></td>
  </tr>

  <tr>
    <td valign="top"><b><fmt:message key="comment.body" /></b></td>
    <td>
      <textarea id="commentBody" name="commentBody" rows="8" cols="40"><c:out value="${comment.body}"/></textarea>
      <div class="small"><b>HTML</b> : b, strong, i, em, blockquote, br, p, pre, a href="", ul, ol, li, sub, sup</div>
    </td>
  </tr>

  <pebble:isNotAuthenticated>
  <tr>
    <td valign="top"><b><fmt:message key="comment.openid.login" /></b></td>
    <td><div id="openIdCommentAuthorProviders">
      <pebble:pluginrenderer plugin="openidcommentauthorprovider"/>
    </div>
      <div id="openIdCommentAuthor" style="display:none">
        <div id="openIdCommentAuthorDetails"> </div>
        (<a href="javascript:logoutOpenIdCommentAuthor()"><fmt:message key="comment.openid.notme"/></a>)
      </div></td>
  </tr>

  <tbody id="commentAuthorDetails">
    <tr>
      <td valign="top"><b><fmt:message key="comment.name" /></b></td>
      <td><input type="text" id="author" name="author" size="40" value="<c:out value="${comment.author}"/>"/></td>
    </tr>

    <tr>
      <td valign="top"><b><fmt:message key="comment.emailAddress" /></b></td>
      <td>
        <input type="text" name="email" size="40" value="<c:out value="${comment.email}"/>"/>
      </td>
    </tr>

    <tr>
      <td valign="top"><b><fmt:message key="comment.website" /></b></td>
      <td><input type="text" name="website" size="40" value="<c:out value="${comment.website}"/>"/></td>
    </tr>
  </tbody>
  </pebble:isNotAuthenticated>

  <pebble:isAuthenticated>
    <tr>
      <td valign="top"><b><fmt:message key="comment.name" /></b></td>
      <td><input type="text" id="author" name="author" size="40" value="<c:out value="${comment.author}"/>" disabled="true" /></td>
    </tr>

    <tr>
      <td valign="top"><b><fmt:message key="comment.emailAddress" /></b></td>
      <td>
        <input type="text" name="email" size="40" value="<c:out value="${comment.email}"/>" disabled="true" />
      </td>
    </tr>

    <tr>
      <td valign="top"><b><fmt:message key="comment.website" /></b></td>
      <td><input type="text" name="website" size="40" value="<c:out value="${comment.website}"/>" disabled="true" /></td>
    </tr>
  </pebble:isAuthenticated>

  <tr>
    <td valign="top"><b><fmt:message key="comment.rememberMe" /></b></td>
    <td>
      <fmt:message key="common.yes"/>&nbsp;
      <input type="radio" name="rememberMe" value="true"
        <c:if test="${rememberMe}">
          checked="checked"
        </c:if>
      />
      <fmt:message key="common.no"/>&nbsp;<input type="radio" name="rememberMe" value="false"
        <c:if test="${not rememberMe}">
          checked="checked"
        </c:if>
      />
    </td>
  </tr>

  <tr>
    <td colspan="2">
      <p>
      <fmt:message key="comment.emailDisclaimer" />
      </p>
    </td>
  </tr>

  <tr>
    <td colspan="2" align="right">
      <input name="submit" type="button" value="<fmt:message key="comment.previewButton"/>" onclick="previewComment();"/>
      <input name="submit" type="submit" value="<fmt:message key="comment.addCommentButton"/>" />
    </td>
  </tr>

</table>
</form>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/fragments/pageable.jsp
<c:if test="${pageable.maxPages > 1}">
  <div align="center">
  <c:if test="${pageable.previousPage > 0}">
    <a href="${url:rewrite(param.url)}&amp;page=${pageable.previousPage}"><fmt:message key="common.previous" /></a>
  </c:if>
  <c:if test="${pageable.minPageRange != 1}">...</c:if>
  <c:forEach var="i" begin="${pageable.minPageRange}" end="${pageable.maxPageRange}">
    <c:choose>
    <c:when test="${i != pageable.page}">
      <a href="${url:rewrite(param.url)}&amp;page=${i}"><fmt:formatNumber value="${i}"/></a>
    </c:when>
    <c:otherwise>
      <fmt:formatNumber value="${i}"/>
    </c:otherwise>
    </c:choose>
  </c:forEach>
  <c:if test="${pageable.maxPageRange != pageable.maxPages}">...</c:if>
  <c:if test="${pageable.nextPage > 0}">
    <a href="${url:rewrite(param.url)}&amp;page=${pageable.nextPage}"><fmt:message key="common.next" /></a>
  </c:if>
  </div>
</c:if>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/fragments/prelude.jspf
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://pebble.sourceforge.net/pebble" prefix="pebble" %>
<%@ taglib prefix="sidebar" tagdir="/WEB-INF/tags/sidebar" %>
<%@ taglib prefix="template" tagdir="/WEB-INF/tags/" %>
<%@ taglib prefix="url" uri="/WEB-INF/url.tld" %>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/fragments/trackbackLinks.jspf
<div class="contentItemLinks">
  <a href="${url:rewrite(trackback.url)}"><fmt:message key="common.readMore" /></a>
  <pebble:isBlogContributor>
  | <input type="checkbox" name="response" value="${trackback.guid}" />
  </pebble:isBlogContributor>
</div>