opensource-programs/JSPWiki-3.0/src/src/java/org/apache/wiki/action/EditActionBean.java
/* 
    JSPWiki - a JSP-based WikiWiki clone.

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.  
 */

package org.apache.wiki.action;

import java.io.IOException;
import java.net.URI;
import java.security.Principal;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.controller.LifecycleStage;
import net.sourceforge.stripes.validation.*;

import org.apache.commons.lang.StringEscapeUtils;
import org.apache.wiki.WikiContext;
import org.apache.wiki.WikiEngine;
import org.apache.wiki.WikiSession;
import org.apache.wiki.api.WikiException;
import org.apache.wiki.api.WikiPage;
import org.apache.wiki.auth.UserManager;
import org.apache.wiki.auth.WikiPrincipal;
import org.apache.wiki.auth.login.CookieAssertionLoginModule;
import org.apache.wiki.auth.permissions.PagePermission;
import org.apache.wiki.auth.user.UserProfile;
import org.apache.wiki.content.ContentManager;
import org.apache.wiki.content.PageNotFoundException;
import org.apache.wiki.content.lock.PageLock;
import org.apache.wiki.filters.RedirectException;
import org.apache.wiki.htmltowiki.HtmlStringToWikiTranslator;
import org.apache.wiki.log.Logger;
import org.apache.wiki.log.LoggerFactory;
import org.apache.wiki.parser.MarkupParser;
import org.apache.wiki.parser.WikiDocument;
import org.apache.wiki.preferences.Preferences;
import org.apache.wiki.preferences.Preferences.TimeFormat;
import org.apache.wiki.providers.ProviderException;
import org.apache.wiki.render.RenderingManager;
import org.apache.wiki.ui.EditorManager;
import org.apache.wiki.ui.stripes.*;
import org.apache.wiki.util.HttpUtil;
import org.apache.wiki.util.TextUtil;
import org.apache.wiki.workflow.DecisionRequiredException;
import org.jdom.JDOMException;

/**
 * ActionBean that manages how users edit and comment on WikiPages.
 */
@HttpCache( allow = false )
@UrlBinding( "/Edit.jsp" )
public class EditActionBean extends AbstractPageActionBean
{
    private static final String LOCK_PREFIX = "lock-";

    private static final Logger log = LoggerFactory.getLogger( EditActionBean.class );

    private String m_author = null;

    private String m_wikiText = null;

    private String m_changenote = null;

    private boolean m_append = false;
    
    private boolean m_overrideConflict = false;

    private Map<String,Boolean> m_options = new HashMap<String,Boolean>();

    private String m_conflictText = null;

    private String m_htmlText = null;

    private String m_email = null;

    private long m_startTime = -1;

    /**
     * AJAX event handler that returns an {@link AjaxResolution} containing
     * a preview of the page contents, as submitted by the {@code wikiText}
     * field.
     * 
     * @return always returns an {@link AjaxResolution} containing the
     * results
     */
    @AjaxEvent
    @HandlesEvent( "preview" )
    @HandlerPermission( permissionClass = PagePermission.class, target = "${page.path}", actions = PagePermission.VIEW_ACTION )
    @WikiRequestContext( "preview" )
    public Resolution preview() throws IOException
    {
        // Parse the wiki markup
        WikiActionBeanContext context = getContext();
        RenderingManager renderer = context.getEngine().getRenderingManager();
        MarkupParser mp = renderer.getParser( context, m_wikiText );
        mp.disableAccessRules();
        WikiDocument doc = mp.parse();

        // Get the text directly from the RenderingManager, without caching
        String result = renderer.getHTML( context, doc );

        // Return an AjaxResolution
        Resolution r = new AjaxResolution( context, result );
        return r;
    }

    /**
     * Event handler method that cancels any locks the user possesses for the
     * current wiki page, and redirects the user to the {@link ViewActionBean}
     * "view" handler.
     * 
     * @return the redirect
     */
    @DontValidate
    @HandlesEvent( "cancel" )
    @HandlerPermission( permissionClass = PagePermission.class, target = "${page.path}", actions = PagePermission.EDIT_ACTION )
    @WikiRequestContext( "cancel" )
    public Resolution cancel()
    {
        WikiPage page = getPage();
        String pagereq = page.getName();
        log.debug( "Cancelled editing " + pagereq );

        // Cancel page lock
        HttpSession session = getContext().getRequest().getSession();
        WikiEngine engine = getContext().getEngine();
        PageLock lock = (PageLock) session.getAttribute( LOCK_PREFIX + pagereq );
        engine.getContentManager().unlockPage( lock );
        session.removeAttribute( LOCK_PREFIX + pagereq );
        return new RedirectResolution( ViewActionBean.class ).addParameter( "page", pagereq );
    }

    @HandlesEvent( "comment" )
    @HandlerPermission( permissionClass = PagePermission.class, target = "${page.path}", actions = PagePermission.COMMENT_ACTION )
    @WikiRequestContext( "comment" )
    public Resolution comment() throws ProviderException
    {
        // Init edit fields and forward to the display JSP
        m_append = true;
        initEditFields( "Commenting on" );
        return new TemplateResolution( "Comment.jsp" );
    }

    /**
     * Loads the page's current text, initializes the EditActionBean for
     * editing, and forwards to the template JSP for the editor; for example,
     * {@code editors/plain.jsp}.
     * @return always returns a {@link ForwardResolution} to the editor JSP
     * @throws ProviderException if the page's current contents cannot
     * be retrieved
     */
    @DefaultHandler
    @HandlesEvent( "edit" )
    @HandlerPermission( permissionClass = PagePermission.class, target = "${page.path}", actions = PagePermission.EDIT_ACTION )
    @WikiRequestContext( "edit" )
    public Resolution edit() throws ProviderException
    {
        // Load the page text
        setWikiText( getPage().getContentAsString() );
        
        // Init edit fields and forward to the display JSP
        initEditFields( "Editing" );
        WikiActionBeanContext context = getContext();
        EditorManager editors = context.getEngine().getEditorManager();
        return new TemplateResolution( editors.getEditorPath( context ) );
    }

    /**
     * Returns whether the edited text should be appended to the page.
     * 
     * @return <code>true</code> if text should be appended;
     *         <code>false</code> otherwise (the default).
     */
    public boolean getAppend()
    {
        return m_append;
    }

    /**
     * Returns the author.
     * 
     * @return the author
     */
    public String getAuthor()
    {
        return m_author;
    }

    /*
     * Returns the changenote for this upload.
     */
    public String getChangenote()
    {
        return m_changenote;
    }

    /**
     * Returns the conflicting text for this page.
     * 
     * @return the text
     */
    public String getConflictText()
    {
        return m_conflictText;
    }

    /**
     * Returns the HTML page text.
     * 
     * @return the HTML page text
     */
    public String getHtmlPageText()
    {
        return m_htmlText;
    }

    /**
     * Returns the email.
     * 
     * @return the email
     */
    public String getEmail()
    {
        return m_email;
    }

    /**
     * Returns the optional settings for the editor. Each setting name is a key in the map,
     * with the vale expressed as a Boolean.
     * @return the options map
     */
    public Map<String,Boolean> getOptions()
    {
        return m_options;
    }

    /**
     * Returns {@code true} when the user has chosen to override
     * another person's changes.
     * @return the result
     */
    public boolean getOverrideConflict()
    {
        return m_overrideConflict;
    }
    
    /**
     * Returns the time the user started editing the page.
     * 
     * @return the start time
     */
    public long getStartTime()
    {
        return m_startTime;
    }

    /**
     * Returns the edited text.
     * 
     * @return the text
     */
    public String getWikiText()
    {
        return m_wikiText;
    }

    /**
     * <p>Initializes default values that must be set in order for events to work
     * properly. This method executes after binding and validation of the
     * ActionBean's other properties, to make sure that the values we want are
     * bound. The values set includes:</p>
     * <ul>
     * <li>the {@code author} property, which is set to the name of the
     * Principal returned by {@link WikiSession#getUserPrincipal()}
     * if the user is authenticated. If the user is anonymous or asserted,
     * the value passed in the request parameter {@code author} is preferred,
     * or the asserted name, or {@code Anonymous Coward} if not asserted.</li>
     * <li>the {@code email} property, which for authenticated users is set
     * to their user profile's e-mail address</li>
     * </ul>
     */
    @After( stages = LifecycleStage.BindingAndValidation )

opensource-programs/JSPWiki-3.0/src/src/WebContent/templates/default/editors/FCK.jsp
<%-- 
    JSPWiki - a JSP-based WikiWiki clone.

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.  
--%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://jakarta.apache.org/jspwiki.tld" prefix="wiki" %>
<%@ taglib uri="http://stripes.sourceforge.net/stripes.tld" prefix="s" %>
<%@ page import="java.util.Properties" %>
<%@ page import="org.apache.commons.lang.*" %>
<%@ page import="org.apache.wiki.*" %>
<%@ page import="org.apache.wiki.action.WikiContextFactory" %>
<%@ page import="org.apache.wiki.api.WikiPage" %>
<%@ page import="org.apache.wiki.auth.*" %>
<%@ page import="org.apache.wiki.auth.permissions.*" %>
<%@ page import="org.apache.wiki.filters.*" %>
<%@ page import="org.apache.wiki.render.*" %>
<%@ page import="org.apache.wiki.parser.JSPWikiMarkupParser" %>
<%@ page import="org.apache.wiki.ui.*" %>
<%@ page import="org.apache.wiki.util.TextUtil" %>
<%@ page errorPage="/Error.jsp" %>
<%--
    This provides the FCK editor for JSPWiki.
--%>
<%  WikiContext context = WikiContextFactory.findContext( pageContext );
    WikiEngine engine = context.getEngine();
    context.setVariable( RenderingManager.WYSIWYG_EDITOR_MODE, Boolean.TRUE );
    context.setVariable( WikiEngine.PROP_RUNFILTERS,  "false" );

    WikiPage wikiPage = context.getPage();
    String originalCCLOption = (String)wikiPage.getAttribute( JSPWikiMarkupParser.PROP_CAMELCASELINKS );
    wikiPage.setAttribute( JSPWikiMarkupParser.PROP_CAMELCASELINKS, "false" );
    
    String usertext = EditorManager.getEditedText(pageContext);
 %>   
<s:layout-render name="${templates['layout/DefaultLayout.jsp']}">

  <%-- Page title should say Edit: + pagename --%>
  <s:layout-component name="headTitle">
    <fmt:message key="edit.title.edit">
      <fmt:param><wiki:Variable var="ApplicationName" /></fmt:param>
      <fmt:param><wiki:PageName/></fmt:param>
    </fmt:message>
  </s:layout-component>

  <%-- Add Javascript for plain editor --%>
  <s:layout-component name="script">
    <script type="text/javascript" src="<wiki:Link format='url' jsp='scripts/jspwiki-edit.js' />"></script>
    <script type="text/javascript" src="<wiki:Link format='url' jsp='scripts/dialog.js' />"></script>
    <script type="text/javascript" src="<wiki:Link format='url' jsp='scripts/fckconfig.js' />"></script>
  </s:layout-component>

  <s:layout-component name="content">
    <%-- FIXME: select CommentLayout or EditorLayout based on "comment" or "edit" event--%>
    <s:layout-render name="${templates['layout/EditorLayout.jsp']}">
      <s:layout-component name="editor">

        <wiki:CheckRequestContext context="edit">
          <wiki:NoSuchPage> <%-- this is a new page, check if we're cloning --%>
        <%
          String clone = request.getParameter( "clone" ); 
          if( clone != null )
          {
            WikiPage p = engine.getPage( clone );
            if( p != null )
            {
                AuthorizationManager mgr = engine.getAuthorizationManager();
                PagePermission pp = new PagePermission( p, PagePermission.VIEW_ACTION );
        
                try
                {            
                  if( mgr.checkPermission( context.getWikiSession(), pp ) )
                  {
                    usertext = engine.getPureText( p );
                  }
                }
                catch( Exception e ) {  /*log.error( "Accessing clone page "+clone, e );*/ }
            }
          }
        %>
          </wiki:NoSuchPage>
        <%
            if( usertext == null )
            {
                usertext = engine.getPureText( context.getPage() );
            }%>
        </wiki:CheckRequestContext>
        <% if( usertext == null ) usertext = "";
        
           RenderingManager renderingManager = new RenderingManager();
           
           // since the WikiProperties are shared, we'll want to make our own copy of it for modifying.
           Properties copyOfWikiProperties = new Properties();
           copyOfWikiProperties.putAll( engine.getWikiProperties() );
           copyOfWikiProperties.setProperty( "jspwiki.renderingManager.renderer", WysiwygEditingRenderer.class.getName() );
           renderingManager.initialize( engine, copyOfWikiProperties );
        	
           String pageAsHtml = StringEscapeUtils.escapeJavaScript( renderingManager.getHTML( context, usertext ) );
           
           // Disable the WYSIWYG_EDITOR_MODE and reset the other properties immediately
           // after the XHTML for FCK has been rendered.
           context.setVariable( RenderingManager.WYSIWYG_EDITOR_MODE, Boolean.FALSE );
           context.setVariable( WikiEngine.PROP_RUNFILTERS,  null );
           wikiPage.setAttribute( JSPWikiMarkupParser.PROP_CAMELCASELINKS, originalCCLOption );
           
           String templateDir = (String)copyOfWikiProperties.get( WikiEngine.PROP_TEMPLATEDIR );
           
           String protocol = "http://";
           if( request.isSecure() )
           {
               protocol = "https://";
           }   
        %>

        <%-- Print any messages or validation errors --%>
        <s:messages />
        <s:errors />
      
        <s:form beanclass="org.apache.wiki.action.EditActionBean"
                    class="wikiform"
                        id="editform"
            acceptcharset="UTF-8"
                  enctype="application/x-www-form-urlencoded">
      
          <%-- If any conflicts, print the conflicting text here --%>
          <c:if test="${not empty wikiActionBean.conflictText}">
            <p>
              <s:label for="conflictText" />
              <s:textarea name="conflictText" readonly="true" />
            </p>
          </c:if>
          
          <%-- EditActionBean relies on these being found.  So be careful, if you make changes. --%>
          <p id="submitbuttons">
            <s:hidden name="page" />
            <s:hidden name="startTime" />
          </p>
          
          <script type="text/javascript">
      //<![CDATA[
      
          var oFCKeditor = new FCKeditor( 'htmlPageText' );
          oFCKeditor.BasePath = 'scripts/fckeditor/';
          oFCKeditor.Value = '<%=pageAsHtml%>';
          oFCKeditor.Width  = '100%';
          oFCKeditor.Height = '450';
          oFCKeditor.Config['CustomConfigurationsPath'] = '<%=request.getContextPath()%>/scripts/fckconfig.js';
          oFCKeditor.Config['StylesXmlPath'] = '<%=request.getContextPath()%>/scripts/fckstyles.xml';
          oFCKeditor.Config['TemplatesXmlPath'] = '<%=request.getContextPath()%>/scripts/fcktemplates.xml';
          oFCKeditor.Config['BaseHref'] = '<%=protocol%><%=request.getServerName()%>:<%=request.getServerPort()%><%=request.getContextPath()%>/';
          oFCKeditor.Config['EditorAreaCSS'] = '<%=request.getContextPath()%>/templates/<%=templateDir%>/jspwiki.css';
          oFCKeditor.Config['SmileyPath'] = oFCKeditor.Config['BaseHref'] + 'scripts/fckeditor/editor/images/smiley/msn/' ;
          oFCKeditor.Create();
      
      //]]>
          </script>
          
          <noscript>
            <div class="error"><fmt:message key="editor.fck.noscript" /></div>
          </noscript>
          
          <p>
            <s:label for="changeNote" />
            <s:text name="changeNote" size="50" maxlength="80" />
          </p>
          
          <wiki:CheckRequestContext context="comment">
            <fieldset>
              <legend><fmt:message key="editor.commentsignature" /></legend>
              <p><s:label for="author" accesskey="n" />&nbsp;<s:text name="author" /></p>
              <p><s:label for="email" accesskey="m" />&nbsp;<s:text name="email" size="24" /></p>
            </fieldset>
          </wiki:CheckRequestContext>
          
          <p>
            <c:set var="saveTitle" scope="page"><fmt:message key="editor.plain.save.title" /></c:set>
            <wiki:CheckRequestContext context='edit'>
              <s:submit name="save" accesskey="s" title="${saveTitle}" />
            </wiki:CheckRequestContext>
            <wiki:CheckRequestContext context='comment'>
              <s:submit name="comment" accesskey="s" title="${saveTitle}" />
            </wiki:CheckRequestContext>
            
            <c:set var="previewTitle" scope="page"><fmt:message key="editor.plain.preview.title" /></c:set>
            <s:submit name="preview" accesskey="v" title="${previewTitle}" />
            
            <c:set var="cancelTitle" scope="page"><fmt:message key="editor.plain.cancel.title" /></c:set>
            <s:submit name="cancel" accesskey="q" title="${cancelTitle}" />
          </p>
      
          <%-- Spam detection fields --%>
          <wiki:SpamProtect />
        </s:form>

      </s:layout-component>
    </s:layout-render>
  </s:layout-component>
  
</s:layout-render>

opensource-programs/JSPWiki-3.0/src/src/WebContent/templates/default/editors/plain.jsp
<%--
    JSPWiki - a JSP-based WikiWiki clone.

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
--%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://jakarta.apache.org/jspwiki.tld" prefix="wiki" %>
<%@ taglib uri="http://stripes.sourceforge.net/stripes.tld" prefix="s" %>
<%@ page errorPage="/Error.jsp" %>
<%--
        This is a plain editor for JSPWiki.
--%>
<s:layout-render name="${templates['layout/DefaultLayout.jsp']}">

  <%-- Page title should say Edit: + pagename --%>
  <s:layout-component name="headTitle">
    <fmt:message key="edit.title.edit">
      <fmt:param><wiki:Variable var="ApplicationName" /></fmt:param>
      <fmt:param><wiki:PageName/></fmt:param>
    </fmt:message>
  </s:layout-component>

  <%-- Add Javascript for plain editor --%>
  <s:layout-component name="script">
    <script type="text/javascript" src="<wiki:Link format='url' jsp='scripts/jspwiki-edit.js' />"></script>
    <script type="text/javascript" src="<wiki:Link format='url' jsp='scripts/dialog.js' />"></script>
  </s:layout-component>

  <s:layout-component name="content">
    <%-- FIXME: select CommentLayout or EditorLayout based on "comment" or "edit" event--%>
    <s:layout-render name="${templates['layout/EditorLayout.jsp']}">
      <s:layout-component name="editor">
        
        <s:form beanclass="org.apache.wiki.action.EditActionBean"
                    class="wikiform"
                        id="editform"
            acceptcharset="UTF-8"
                  enctype="application/x-www-form-urlencoded">
      
          <%-- Toolbar --%>
          <div id="toolbar" class="line">
      
            <div id="configDialog" style="display:none;">
              <s:checkbox name="options.tabCompletion" id="tabCompletion" /><fmt:message key="editor.plain.tabcompletion"/>
              <br />
              <s:checkbox name="options.smartPairs" id="smartPairs" /><fmt:message key="editor.plain.smartpairs"/>
            </div>
        
            <fieldset class="unit">
              <legend><fmt:message key='editor.plain.action'/></legend>
              <a href="#" class="tool tUNDO" title="<fmt:message key='editor.plain.undo.title'/>">undo</a>
              <a href="#" class="tool tREDO" title="<fmt:message key='editor.plain.redo.title'/>">redo</a>
              <a href="#" class="tool tSEARCH" title="<fmt:message key='editor.plain.find.title'/>">find</a>
              <a href="#" class="tool tCONFIG" title="<fmt:message key='editor.plain.config.title'/>">config</a>
            </fieldset>
        
            <fieldset class="unit">
              <legend><fmt:message key='editor.plain.insert'/></legend>
              <a href="#" class="tool tLink" title="<fmt:message key='editor.plain.tbLink.title'/>">link</a>
              <a href="#" class="tool tH1" title="<fmt:message key='editor.plain.tbH1.title'/>">h1</a>
              <a href="#" class="tool tH2" title="<fmt:message key='editor.plain.tbH2.title'/>">h2</a>
              <a href="#" class="tool tH3" title="<fmt:message key='editor.plain.tbH3.title'/>">h3</a>
              <a href="#" class="tool tPRE" title="<fmt:message key='editor.plain.tbPRE.title'/>">pre</a>
              <a href="#" class="tool tHR" title="<fmt:message key='editor.plain.tbHR.title'/>">hr</a>
              <a href="#" class="tool tBR" title="<fmt:message key='editor.plain.tbBR.title'/>">br</a>
              <a href="#" class="tool tCHAR" title="<fmt:message key='editor.plain.tbCHAR.title'/>">special</a>
            </fieldset>
        
            <fieldset class="unit">
              <legend><fmt:message key='editor.plain.style'/></legend>
              <a href="#" class="tool tB" title="<fmt:message key='editor.plain.tbB.title'/>">bold</a>
              <a href="#" class="tool tI" title="<fmt:message key='editor.plain.tbI.title'/>">italic</a>
              <a href="#" class="tool tMONO" title="<fmt:message key='editor.plain.tbMONO.title'/>">mono</a>
              <a href="#" class="tool tCSS" title="<fmt:message key='editor.plain.tbCSS.title'/>">%%</a>
              <a href="#" class="tool tFONT" title="<fmt:message key='editor.plain.tbFONT.title'/>">font</a>
              <a href="#" class="tool tCOLOR" title="<fmt:message key='editor.plain.tbCOLOR.title'/>">color</a>
              <!--
              <a href="#" class="tool tSUP" title="<fmt:message key='editor.plain.tbSUP.title'/>">sup</a>
              <a href="#" class="tool tSUB" title="<fmt:message key='editor.plain.tbSUB.title'/>">sub</a>
              <a href="#" class="tool tSTRIKE" title="<fmt:message key='editor.plain.tbSTRIKE.title'/>">strike</a>
              -->
            </fieldset>
        
            <fieldset class="unit">
              <legend><fmt:message key='editor.plain.extra'/></legend>
              <a href="#" class="tool tACL" title="<fmt:message key='editor.plain.tbACL.title'/>">acl</a>
              <a href="#" class="tool tIMG" title="<fmt:message key='editor.plain.tbIMG.title'/>">img</a>
              <a href="#" class="tool tTABLE" title="<fmt:message key='editor.plain.tbTABLE.title'/>">table</a>
              <a href="#" class="tool tPLUGIN" title="<fmt:message key='editor.plain.tbPLUGIN.title'/>">plugin</a>
              <%--
              <a href="#" class="tool tTOC" title="<fmt:message key='editor.plain.tbTOC.title'/>">toc</a>
              --%>
              <a href="#" class="tool tDL" title="<fmt:message key='editor.plain.tbDL.title'/>">dl</a>
              <a href="#" class="tool tCODE" title="<fmt:message key='editor.plain.tbCODE.title'/>">code</a>
              <a href="#" class="tool tTAB" title="<fmt:message key='editor.plain.tbTAB.title'/>">tab</a>
              <a href="#" class="tool tSIGN" title="<fmt:message key='editor.plain.tbSIGN.title'/>">sign</a>
              <%-- --%>
            </fieldset>
        
            <div id="findDialog" style="display:none;clear:both;">
              <input type="text" name="tbFIND" id="tbFIND" size="16" value="find"/>
              <s:checkbox name="options.findMatchCase" /><fmt:message key="editor.plain.matchcase"/>
              <s:checkbox name="options.findRegex" /><fmt:message key="editor.plain.regexp"/>
              <input type="text" name="tbREPLACE" id="tbREPLACE" size="16" />
              <s:button class="btn" id="doreplace" name="findAndReplace" />
              <s:checkbox name="options.findGlobal" /><fmt:message key="editor.plain.global"/>
            </div>
      
          </div><%-- end of the toolbar --%>
      
          <%-- Print any messages or validation errors --%>
          <s:messages />
          <s:errors />
      
          <%-- If any conflicts, print the conflicting text here --%>
          <c:if test="${not empty wikiActionBean.conflictText}">
            <p>
              <s:label for="conflictText" />
              <s:textarea name="conflictText" readonly="true" />
            </p>
            <p>
              <s:checkbox name="overrideConflict" />
              <fmt:message key="overrideConflict" />
            </p>
          </c:if>
      
          <%-- You knew this would be here somewhere. Yes, it's the textarea where the user
                actually edits stuff. --%>
          <div id="editor-content" class="line" style="clear:both;">
      
            <div class="unit" style="width:98%;">
              <div class="editor-container">
              <%-- js-insert: <div id="snipetoc"><ul>...</ul></div> --%>
              <s:textarea id="wikiText" name="wikiText" class="editor" rows="20" cols="80" />
              <%-- js insert: <div class="resize-bar"></div>  --%>
              </div>
            </div>
      
            <div class="unit size1of2 lastUnit">
              <div id="previewspin" class="spin" style="display:none;"><fmt:message key="common.ajax.loading"/></div>
              <div id="livepreview" class="xflow"></div>
      	    </div>
      
          </div>
      
          <%-- Fields for changenote, renaming etc. --%>
          <table>
            <tr>
              <td>
                <s:label for="changenote" />
              </td>
              <td>
                <s:text name="changenote" size="50" maxlength="80" />
              </td>
            </tr>
            <wiki:UserCheck status="anonymous">
              <tr>
                <td><s:label for="author" accesskey="n" /></td>
                <td><s:text name="author" /></td>
              </tr>
              <wiki:CheckRequestContext context="comment">
                <tr>
                  <td><s:label for="email" accesskey="m" /></td>
                  <td><s:text name="email" size="24" /></td>
                </tr>
              </wiki:CheckRequestContext>
            </wiki:UserCheck>
          </table>
      
          <%-- Spam detection fields and optional CAPTCHA --%>
          <wiki:SpamProtect />
      
          <%-- EditActionBean relies on these being found.  So be careful, if you make changes. --%>
          <p id="submitbuttons">
            <s:hidden name="page" />
            <s:hidden name="startTime" />
            <s:hidden name="append" />
            <s:submit name="save" />
            <s:submit name="cancel" />
          </p>
        </s:form>
        
      </s:layout-component>
    </s:layout-render>
  </s:layout-component>
  
</s:layout-render>