opensource-programs/pebble-2.6.4/src/src/main/java/net/sourceforge/pebble/domain/MultiBlog.java
/*
 * Copyright (c) 2003-2011, Simon Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   - Neither the name of Pebble nor the names of its contributors may
 *     be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package net.sourceforge.pebble.domain;

import net.sourceforge.pebble.comparator.BlogEntryComparator;
import net.sourceforge.pebble.PebbleContext;

import javax.servlet.http.HttpServletRequest;
import java.util.*;

/**
 * A composite blog is one that is made up of one or more simple blogs. This
 * is effectively a container when Pebble is running in multi-user mode - there
 * being a single MultiBlog and many Blog instances.
 * <br /><br />
 * In addition to managing one or more simple blogs, a composite blog provides
 * some aggegration functionality over the blogs it manages in order to
 * generate an aggregated XML (RSS/RDF/Atom) feed.
 *
 * @author    Simon Brown
 */
public class MultiBlog extends AbstractBlog {

  /**
   * Creates a new Blog instance, based at the specified location.
   *
   * @param root    an absolute path pointing to the root directory of the blog
   */
  public MultiBlog(String root) {
    super(root);

    // probably MultiBlog should be made a final class if init is called from here - 
    // see javadoc comment on AbstractBlog.init() for reasons
    init();
  }

  /**
   * Gets the default properties for a MultiBlog.
   *
   * @return    a Properties instance
   */
  protected Properties getDefaultProperties() {
    Properties defaultProperties = new Properties();
    defaultProperties.setProperty(NAME_KEY, "My blogs");
    defaultProperties.setProperty(DESCRIPTION_KEY, "");
    defaultProperties.setProperty(IMAGE_KEY, "");
    defaultProperties.setProperty(AUTHOR_KEY, "Various");
    defaultProperties.setProperty(TIMEZONE_KEY, "Europe/London");
    defaultProperties.setProperty(RECENT_BLOG_ENTRIES_ON_HOME_PAGE_KEY, "3");
    defaultProperties.setProperty(LANGUAGE_KEY, "en");
    defaultProperties.setProperty(COUNTRY_KEY, "GB");
    defaultProperties.setProperty(CHARACTER_ENCODING_KEY, "UTF-8");
    defaultProperties.setProperty(THEME_KEY, "default");

    return defaultProperties;
  }

  /**
   * Gets the ID of this blog.
   *
   * @return the ID as a String
   */
  public String getId() {
    return "";
  }

  /**
   * Gets the URL where this blog is deployed.
   *
   * @return a URL as a String
   */
  public String getUrl() {
    return PebbleContext.getInstance().getConfiguration().getUrl();
  }

  /**
   * Gets the relative URL where this blog is deployed.
   *
   * @return a URL as a String
   */
  public String getRelativeUrl() {
    return "/";
  }

  /**
   * Gets the date that this blog was last updated.
   *
   * @return  a Date instance representing the time of the most recent entry
   */
  public Date getLastModified() {
    Date date = new Date(0);

    Iterator it = BlogManager.getInstance().getPublicBlogs().iterator();
    Blog blog;
    while (it.hasNext()) {
      blog = (Blog)it.next();
      if (blog.getLastModified().after(date)) {
        date = blog.getLastModified();
      }
    }

    return date;
  }

  /**
   * Gets the most recent blog entries, the number
   * of which is specified.
   *
   * @param numberOfEntries the number of entries to get
   * @return a List containing the most recent blog entries
   */
  public List<BlogEntry> getRecentBlogEntries(int numberOfEntries) {
    List<BlogEntry> blogEntries = new ArrayList<BlogEntry>();

    for (Blog blog : BlogManager.getInstance().getPublicBlogs()) {
      blogEntries.addAll(blog.getRecentPublishedBlogEntries());
    }

    Collections.sort(blogEntries, new BlogEntryComparator());

    if (blogEntries.size() >= numberOfEntries) {
      return new ArrayList<BlogEntry>(blogEntries).subList(0, numberOfEntries);
    } else {
      return new ArrayList<BlogEntry>(blogEntries);
    }
  }

  /**
   * Logs this request for blog.
   *
   * @param request   the HttpServletRequest instance for this request
   */
  public void log(HttpServletRequest request, int status) {
    // no op
  }

}

opensource-programs/pebble-2.6.4/src/src/main/java/net/sourceforge/pebble/domain/StaticPage.java
/*
 * Copyright (c) 2003-2011, Simon Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   - Neither the name of Pebble nor the names of its contributors may
 *     be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package net.sourceforge.pebble.domain;

import net.sourceforge.pebble.util.StringUtils;
import net.sourceforge.pebble.web.validation.ValidationContext;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Represents a page.
 *
 * @author Simon Brown
 */
public class StaticPage extends PageBasedContent {

	public static final String TEMPLATE_PROPERTY = "template";
	
  /** the name of the page */
  private String name;
  
  /** the name of the template **/
  private String template = TEMPLATE_PROPERTY;

  /**
   * Creates a new blog entry.
   *
   * @param blog    the owning Blog
   */
  public StaticPage(Blog blog) {
    super(blog);
    setPublished(true);
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = StringUtils.transformHTML(name);
  }

  /**
   * Gets a list of all tags.
   *
   * @return  a List of tags
   */
  public List<Tag> getAllTags() {
    List<Tag> list = new ArrayList<Tag>(getTagsAsList());
    Collections.sort(list);

    return list;
  }

  /**
   * Gets a permalink for this blog entry that is local to the blog. In other
   * words, it doesn't take into account the original permalink for
   * aggregated content.
   *
   * @return an absolute URL as a String
   */
  public String getLocalPermalink() {
    return getBlog().getUrl() + "pages/" + name + ".html";
  }

  public void validate(ValidationContext context) {
	// TODO: localize
    if (name == null || name.length() == 0) {
      context.addError("Name cannot be empty");
    } else if (!name.matches("[\\w_/-]+")) {
      context.addError("Name \"" + StringUtils.transformHTML(name) + "\" must contain only A-Za-z0-9_-/");
    }

    String id = getBlog().getStaticPageIndex().getStaticPage(name);
    if (id != null && !id.equals(getId())) {
      context.addError("A page with the name \"" + name + "\" already exists");
    }
  }

  public String getGuid() {
    return "page/" + getBlog().getId() + "/" + getId();
  }

  public void setTemplate(String newTemplate) {
    propertyChangeSupport.firePropertyChange(TEMPLATE_PROPERTY, template, newTemplate);
    this.template = newTemplate;
  }
  
  public String getTemplate() {
    return template;
  }
  
  /**
   * Indicates whether some other object is "equal to" this one.
   *
   * @param o   the reference object with which to compare.
   * @return <code>true</code> if this object is the same as the obj
   *         argument; <code>false</code> otherwise.
   * @see #hashCode()
   * @see java.util.Hashtable
   */
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }

    if (!(o instanceof StaticPage)) {
      return false;
    }

    StaticPage staticPage = (StaticPage)o;
    return getGuid().equals(staticPage.getGuid());
  }

  /**
   * Creates and returns a copy of this object.
   *
   * @return a clone of this instance.
   * @see Cloneable
   */
  public Object clone() {
    StaticPage page = new StaticPage(getBlog());
    page.setEventsEnabled(false);
    page.setPersistent(isPersistent());
    page.setTitle(getTitle());
    page.setSubtitle(getSubtitle());
    page.setBody(getBody());
    page.setDate(getDate());
    page.setState(getState());
    page.setAuthor(getAuthor());
    page.setOriginalPermalink(getOriginalPermalink());
    page.setName(getName());
    page.setTags(getTags());
    page.setLockedBy(getLockedBy());
    page.setTemplate(getTemplate());

    return page;
  }

}

opensource-programs/pebble-2.6.4/src/src/main/java/net/sourceforge/pebble/web/action/FileAction.java
/*
 * Copyright (c) 2003-2011, Simon Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   - Neither the name of Pebble nor the names of its contributors may
 *     be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package net.sourceforge.pebble.web.action;

import net.sourceforge.pebble.Constants;
import net.sourceforge.pebble.domain.MultiBlog;
import net.sourceforge.pebble.domain.FileManager;
import net.sourceforge.pebble.domain.Blog;
import net.sourceforge.pebble.service.LastModifiedService;
import net.sourceforge.pebble.util.FileUtils;
import net.sourceforge.pebble.web.view.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.File;
import java.util.Calendar;
import java.util.Date;

/**
 * Gets a file/image from a blog.
 *
 * @author    Simon Brown
 */
public class FileAction extends Action {

  /** the log used by this class */
  private static final Log log = LogFactory.getLog(FileAction.class);

  @Inject
  private LastModifiedService lastModifiedService;

  /**
   * Peforms the processing associated with this action.
   *
   * @param request  the HttpServletRequest instance
   * @param response the HttpServletResponse instance
   * @return the name of the next view
   */
  public View process(HttpServletRequest request, HttpServletResponse response) throws ServletException {
    Object o = request.getAttribute(Constants.BLOG_KEY);
    if (o instanceof MultiBlog) {
      return new NotFoundView();
    }

    Blog blog = (Blog)getModel().get(Constants.BLOG_KEY);

    String name = request.getParameter("name");
    String type = request.getParameter("type");
    if (name == null || name.length() == 0 || name.equals("/")) {
      // forward to secure file browser
      return new ForwardView("/viewFiles.secureaction?type=" + type);
    }

    FileManager fileManager = new FileManager(blog, type);
    File root = fileManager.getRootDirectory();
    File file = fileManager.getFile(name);

    if (!file.exists()) {
      // file doesn't exist so send back a 404
      return new NotFoundView();
    }

    if (!FileUtils.underneathRoot(root, file) || file.isDirectory()) {
      // forward to secure file browser
      return new ForwardView("/viewFiles.secureaction?type=" + type + "&path=" + name);
    }

    Date lastModified = new Date(file.lastModified());
    Calendar expires = blog.getCalendar();
    expires.add(Calendar.MONTH, 1);

    if (lastModifiedService.checkAndProcessLastModified(request, response, lastModified, expires.getTime())) {
      return new NotModifiedView();
    } else {
      return new FileView(file);
    }
  }

}

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/blogEntryListeners.jsp
<div class="contentItem">
  <h1>Blog Entry Listeners</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <p>
      Blog entry listeners are a type of Pebble plugin that allow custom code to be called
      whenever a blog entry is added, removed, changed, published or unpublished. The following blog entry listeners are included with the Pebble distribution and those
      marked with a (*) are configured by default.
    </p>

    <p>
      <b>net.sourceforge.pebble.event.blogentry.XmlRpcNotificationListener</b> (*)<br />
      Sends an <a href="./help/xmlrpcUpdatePings.html">XML-RPC update notification ping</a> when a blog entry is published.
    </p>

    <p>
      <b>net.sourceforge.pebble.event.blogentry.EmailNotificationListener</b><br />
      Sends a notification e-mail to the blog owner when a new blog entry is added, changed or published.
    </p>

    <p>
      <b>net.sourceforge.pebble.event.blogentry.PostToTwitterBlogEntryListener</b><br />
      Post the title and a tinyurl to twitter when a new blog entry is published. This requires the 
      plugin properties twitter.username and twitter.password to be configured.
    </p>

    <p>
      <b>net.sourceforge.pebble.event.blogentry.MarkUnpublishedListenerener</b><br />
      Marks all new and changed blog entries to be unpublished, so that they require approval from the blog owner before being published on the blog. Only the following subset of
      properties, when changed, will cause a blog entry to be marked as unpublished.
    </p>

    <ul>
      <li>Title</li>
      <li>Subtitle</li>
      <li>Excerpt</li>
      <li>Body</li>
      <li>Original permalink</li>
    </ul>

    <h3>Configuring blog entry listeners</h3>
    <p>
      To configure the blog entry listeners used by your blog, modify the list on the <a href="viewPlugins.secureaction#blogEntryListeners">Plugins</a> page. Your blog is using the
      following blog entry listeners.
    </p>
    <pre class="codeSample"><c:forEach var="listener" items="${blog.eventListenerList.blogEntryListeners}">${listener.class.name}<br /></c:forEach></pre>
  </div>
</div>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/bloggerApi.jsp
<div class="contentItem">
  <h1>Blogger API</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <p>
      Pebble has a comprehensive web-based administration interface but it also supports the Blogger API for managing your blog content via compatible blogging clients. Examples here include MarsEdit, ecto, w.bloggar and others.
    </p>

    <h3>Configuration</h3>
    <p>
      When configuring a blogging client, you will typically be asked for the following information.
    </p>

    <ul>
      <li>Username : ${authenticatedUser.username}</li>
      <li>Password : (the same you used to login here)</li>
      <li>XML-API : blogger</li>
      <li>XML-RPC URL : ${pebbleContext.configuration.url}xmlrpc/</li>
      <li>Blog ID : ${blog.id}</li>
    </ul>

    <h3>Titles and Categories</h3>
    <p>
      Because the Blogger API is fairly simplistic, it has no support for things like blog entry titles and categories. However, with Pebble, it possible to specify these attributes for your blog entry. To do this, simply prepend your blog entry body with <code>&lt;title&gt;Your title here&lt;/title&gt;</code> and/or <code>&lt;category&gt;/categoryId1,/categoryId2&lt;/category&gt;</code>.
      Alternatively, consider using the <a href="./help/metaWeblogApi.html">MetaWeblog API</a>.
    </p>
  </div>
</div>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/comments.jsp
<div class="contentItem">
  <h1>Comments</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <p>
      Pebble allows visitors to leave comments on your blog entries and although comments are enabled for new blog entries by default, they can be disabled so that comments can't be left.
      The number of comments for any blog entry is shown underneath the blog entry itself along with a "Responses[x]" link that takes you to the comments for that entry.
      Pebble supports nested comments for threads of conversation and allows readers to preview their comments before posting them to your blog.
    </p>


    <h3>Removing comments</h3>
    <p>
      If for any reason you want to remove a comment, just check the checkbox next to it and click the "Remove" button at the bottom of the page. The e-mail and IP address of the comment author are not published on your blog, only logged in users can see this information.
    </p>

    <h3>E-mail notifications</h3>
    <p>
      Pebble can be configured to create an e-mail notification when new comments are added, sending it to the blog owner and
      anybody that has left a comment for that blog entry and specified their e-mail address. To encourage further
      discussion via comments and prevent e-mail addresses being harvested for spam, a separate e-mail is sent to each person.
    </p>

    <p>
      To enable e-mail notifications, ensure that your e-mail address is defined on the
      <a href="viewBlogProperties.secureaction">Blog properties</a> page and add the following class name to the list of
      comment listeners on the <a href="viewPlugins.secureaction">plugins</a> page.
    </p>

    <pre class="codeSample">net.sourceforge.pebble.listenerner.comment.EmailNotificationListener</pre>

    <p>
      Readers can opt-out of these e-mails on a per blog entry basis by clicking the opt-out link in the e-mail.
      This will remove their e-mail address from any comments that they have made on that blog entry so they will
      not receive any more e-mails when further comments are added.
    </p>

    <h3>Comment moderation and spam</h3>
    <p>
      For more information about how to deal with comment spam, please see <a href="./help/responseSpam.html">Comment and TrackBack Spam</a>.
    </p>
  </div>
</div>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/faq.jsp
<div class="contentItem">
  <h1>Frequently Asked Questions</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <b>Configuration</b><br />
    <ol>
      <li><b>I've installed Pebble to my server, but where is my blog data being stored?</b><br />After logging in to your blog, click the View configuration link to see where your data is being stored. By default, blog data is saved into a <code>blog</code> subdirectory inside your home directory.</li>
      <li><b>I've started Pebble and all of the blog data is being saved into a <code>blog</code> subdirectory inside my home directory. How can I change this?</b> You can change the value of the <code>blog.dir</code> property in the <code>pebble.properties</code> file. See <a href="getting-started.html">getting started</a> for more information.</li>
    </ol>

    <b>Blog entries</b><br />
    <ol>
      <li><b>I'm setting up a team blog and I'd like all blog entries to be approved before publication. Is this possible?</b> Yes, see <a href="./help/blogEntries.html#moderation">Blog entry moderation</a> for more details.</li>
    </ol>

    <b>Comments and TrackBacks</b><br />
    <ol>
      <li><b>My blog has been getting some comment/TrackBack spam recently, what can I do about this?</b> Pebble has several features to fight spam. See <a href="commentAndTrackbackSpam.jsp">Comment and TrackBack Spam</a> for more details.</li>
      <li><b>My blog has just received a lot of spam, how can I clean this up?</b> See <a href="commentAndTrackbackSpam.jsp#bulkManagement">Comment and TrackBack Spam</a> for details on the bulk comment and TrackBack management features.</li>
    </ol>

    <b>Technical</b><br />
    <ol>
      <li><b>What technologies does Pebble use?</b> Pebble uses standard J2SE and J2EE technologies such as JSP, servlets, filters, JSP custom tags, JSTL and JAXP.</li>
      <li><b>Can Pebble store content in a relational database?</b> In theory, yes. The peristence tier is designed to be extensible although only the single implementation exists at the moment.</li>
    </ol>
  </div>

</div>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/files.jsp
<div class="contentItem">
  <h1>Files</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <p>
      In the same way that images can be uploaded and linked to, Pebble allows arbitrary files to be uploaded to your blog for download by your readers. To do this, click <a href="./files/">Files</a>.
    </p>

    <h3><a name="mimeTypes"></a>MIME types</h3>
    <p>
      If, when opening/downloading files from your blog, you notice that the appropriate MIME type is not being set, this can be
      rectified by adding an entry into the <code>/WEB-INF/classes/content-types.properties</code> file. A MIME type entry takes
      the form <code>&lt;file extension&gt;=&lt;MIME type&gt;</code> and an example is as follows:
      <pre>  .mp3=audio/x-mpeg</pre>
      Pebble needs to be restarted for MIME type changes to take effect.
    </p>
  </div>
</div>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/managingUsers.jsp
<div class="contentItem">
  <h1>Managing Users</h1>
  <h2></h2>

  <div class="contentItemBody">
    <p>
      As a blog admin user, you can manage user information stored in the security realm. This includes the ability
      to create new users, modify their user details (name, e-mail address, website and roles), remove users and reset passwords.
      To access these features, click the <a href="${pageContext.request.contextPath}/viewUsers.secureaction">Users</a> link.
    </p>

    <h3>Default password</h3>
    <p>
      The default password, for new users and password resets, is <code>password</code>.
    </p>

  </div>
</div>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/metaWeblogApi.jsp
<div class="contentItem">
  <h1>MetaWeblog API</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <p>
      Pebble has a comprehensive web-based administration interface but it also supports the MetaWeblog API for managing your blog content via compatible blogging clients. Examples here include MarsEdit, ecto, w.bloggar and others.
    </p>

    <h3>Configuration</h3>
    <p>
      When configuring a blogging client, you will typically be asked for the following information.
    </p>

    <ul>
      <li>Username : ${authenticatedUser.username}</li>
      <li>Password : (the same you used to login here)</li>
      <li>XML-API : metaWeblog</li>
      <li>XML-RPC URL : ${pebbleContext.configuration.url}xmlrpc/</li>
      <li>Blog ID : ${blog.id}</li>
    </ul>

    <h3>Uploading images and files</h3>
    <p>
      With the MetaWeblog API you can upload images and other files to your blog.
      By default, any files you upload will be stored underneath <a href="./images/">Images</a>.
      To explicitly specify where the file should be uploaded to, prefix the filename with
      <code>images/</code> or <code>files/</code> to store the file under the <a href="./images/">Images</a> or <a href="./files/">Files</a> respectively. If required, you can also specify a directory structure in the filename such as <code>images/2004/someimage.jpg</code>.
    </p>
  </div>
</div>

opensource-programs/pebble-2.6.4/src/src/main/webapp/WEB-INF/help/permalinkProviders.jsp
<div class="contentItem">
  <h1>Permalink Providers</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <p>
      Permalink Providers are a type of Pebble plugin that changes the way
      permalinks are generated and handled. The following implementations are included in the distribution.
    </p>

    <p>
      <b>net.sourceforge.pebble.permalink.DefaultPermalinkProvider</b><br />
      Generates permalinks of the form /yyyy/mm/dd/time-in-millis.html (this is the default)
      <br /><br />
      <b>net.sourceforge.pebble.permalink.ShortPermalinkProvider</b><br />
      Generates permalinks of the form /time-in-millis.html
      <br /><br />
      <b>net.sourceforge.pebble.permalink.TitlePermalinkProvider</b><br />
      Generates permalinks of the form /yyyy/mm/dd/each_word_in_the_title.html
    </p>

    <p>
      By default, Pebble will use the <code>DefaultPermalinkProvider</code>. To change this,
      modify the permalink provider on the <a href="viewPlugins.secureaction#permalinkProvider">Plugins</a> page.
      If another is chosen, Pebble will additionally use the <code>DefaultPermalinkProvider</code> as a fallback, which means you can change
      your permalink provider and retain backwards compatibility with permalinks that have already been published.
    </p>
  </div>
</div>